### PR TITLE
Add option to send message using messagebox

### PR DESCRIPTION
**Pull request by Zefau**
added server part to send message via messagebox

### CODE REVIEW

**Comment by Zefau** [comment]
added client part to send message via messagebox

**Comment by Zefau** [comment]
@GermanBluefox please merge. travis fails for this pr because it fails for the whole repo

**Comment by GermanBluefox** [comment]
Thank you!
Please add description of messages to README.md.

**Comment by Zefau** [comment]
Added description to README.md

**Comment by Zefau** [comment]
@GermanBluefox please merge, thanks!

**Pull request merged**
