### PR TITLE
remove adapter.getMessage and minor fixes

### PR DESCRIPTION
**Pull request by foxriver76**
- usage of eslint
- applied eslint
- fixed usage of undefined variables

### CODE REVIEW

**Comment by foxriver76** [comment]
Tests are failing for a few months now. Maybe increasing the timeouts (setTimeouts used in the affected tests) helps.

**Comment by Apollon77** [comment]
No reasons are (whyever) that in some combinations the mqtt server can not be started to listen to the relevant port

**Comment by foxriver76** [comment]
If i run it on my local setup, then the port problem appears in some scenarios, but on the CI server it looks different.
https://travis-ci.org/ioBroker/ioBroker.mqtt/jobs/657259054#L963

**Comment by Apollon77** [comment]
aahhh this error is new :-)

**Comment by Apollon77** [comment]
this error might be because of js-controller 2.x changes abecause the "upload" state only exists now if relevant and could be that it is not there. so the used state should be changed to one which exists in any case :-)

**Comment by foxriver76** [comment]
IMHO there is no `system.adapter` object left, where we can rely on, that the state won't change due to internal reasons in the meantime. However, we could use another foreign state like of admin.0 if this is suitable for the test scenario. I also don't think that someone should write in `system.adapter` objects, which are handled by the controller

**Comment by Apollon77** [comment]
relying on a system.adapter.x state in any case ia  a bad idea as we learned in the meantime :-)

SO better is to create a test.0.xy state for that especially ( I already migrated other tests todo so). if you want to change kess then system.adapter.mqtt.xy should be there in this case in any case :-)

**Comment by foxriver76** [comment]
I've created a fictitious foreign adapter object now. Tests passing.

**Comment by GermanBluefox** [comment]
Thank you.

**Pull request merged**
